version: '3'

services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 8000:80
    volumes:
      # nginx settings
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      # gikenweb pages
      - ./static:/var/www/html
      - ./other-app:/var/www/html/other-app
    depends_on:
      - todo_app
  todo_app:
    build:
      context: ./goApp/TodoApp
    command: go run server.go
    volumes:
      - goApp/TodoApp:/app
    depends_on:
      - postgre
  postgres:
    image: postgres:9.2-alpine
    volumes:
      # 初期データ投入用
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      # データ保持用
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  pgadmin:
    image: dpage/pgadmin4:4.29
    ports:
      - 8001:80
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
