# ワークフローの名前
name: Go

# ワークフローをトリガーするGitHubイベントの名前
on:
  push:
    branches: [ feature/38 ]
#    paths:
#      - '**.go'
  pull_request:
    branches: [ feature/38 ]

jobs:
  build:
#    env: ${{ }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v -o /home/runner/work/goApp/TodoApp/server.go

#      - name: Test
#        run: go test -v ./...
