# ワークフローの名前
name: Go

# ワークフローをトリガーするGitHubイベントの名前
on:
  push:
    branches: [ feature/38 ]
  # paths:
  # - '**.go'
  pull_request:
    branches: [ feature/38 ]

jobs:
  build:
    #    env: ${{ }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # feature/38にcheckoutする
        with:
          ref: feature/38

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: GoBuild
        run: |
          pwd
          cd $GITHUB_WORKSPACE/goApp/TodoApp
          pwd
          go build -v -o $GITHUB_WORKSPACE/goApp/TodoApp

#      - name: Test
#        run: go test -v ./...
